# Generated by Django 3.2 on 2021-06-02 07:21

from django.db import migrations, models
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', main.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('guildid', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('funinspire', models.CharField(max_length=50)),
                ('funcomeback', models.CharField(max_length=50)),
                ('funcat', models.CharField(max_length=50)),
                ('fundog', models.CharField(max_length=50)),
                ('funfox', models.CharField(max_length=50)),
                ('basicping', models.CharField(max_length=50)),
                ('adminquit', models.CharField(max_length=50)),
                ('adminchangeprefix', models.CharField(max_length=50)),
                ('admintest', models.CharField(max_length=50)),
            ],
        ),
    ]
