# Generated by Django 3.2 on 2021-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('guildid', models.BigIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=100)),
                ('roles', models.TextField()),
                ('membercount', models.IntegerField()),
            ],
        ),
    ]
