# Generated by Django 3.2 on 2021-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privileges',
            name='guildowner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
