# Generated by Django 3.2 on 2021-06-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_privileges_guildowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privileges',
            name='guildowner',
        ),
    ]
