# Generated by Django 3.2 on 2021-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_timeperweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(),
        ),
    ]
