# Generated by Django 3.2.3 on 2021-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210604_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedGuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildid', models.BigIntegerField()),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
