# Generated by Django 3.2.3 on 2021-06-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_connectedguilds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedguilds',
            name='name',
        ),
    ]
