# Generated by Django 3.2 on 2021-05-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210525_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
