# Generated by Django 3.2 on 2021-05-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_jobs_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
