# Generated by Django 3.2 on 2021-06-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jobs_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerType',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='TimePerWeek',
        ),
    ]
