# Generated by Django 3.2 on 2021-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='privileges',
            name='userid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
