# Generated by Django 3.2 on 2021-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_privileges_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='privileges',
            name='guildid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
