# Generated by Django 3.2 on 2021-06-02 06:12

from django.db import migrations
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_discorduser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', main.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
