# Generated by Django 3.2 on 2021-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_discorduser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.BooleanField(null=True),
        ),
    ]
