# Generated by Django 3.2 on 2021-06-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_discorduser_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
