# Generated by Django 3.2 on 2021-06-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_themes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
